- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-centos7.yml
  when: ansible_os_family == 'RedHat'

- include: setup-ubuntu16.yml
  when: ansible_distribution == 'Ubuntu'

- inclide: create_testpage
  copy: src=index.php dest=/var/www/{{ domname }} 
